# Generated by Django 5.1.2 on 2024-11-14 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestquests',
            name='quest',
        ),
        migrations.RemoveField(
            model_name='newquests',
            name='quest',
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quests'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Bestquests',
        ),
        migrations.DeleteModel(
            name='Newquests',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
